### ISSUE TITLE
Add Basic Array code (Traverse, Insertion, Deletion, Search, Update )

### ISSUE THREAD

**Issue by kuldeepsingh33** [kuldeepsingh33/DSA-Basic#1]

**Comment by EnggKrishna** [comment]
hii @kuldeepsingh33 please assign this to me

**Comment by kuldeepsingh33** [comment]
@codemii  , Now you can work on this issue.

**Comment by RavishGupta** [comment]
please assign this issue to me

**Comment by kuldeepsingh33** [comment]
Now you can work @RavishGupta

**Comment by Pr3mKum4r** [comment]
Hey Can u plz assign me i want to add array ADT

**Comment by kuldeepsingh33** [comment]
@Pr3mKum4r let me assign you this issue , now you can work on it .
