### ISSUE TITLE
Add Binary Search Code In Java

### ISSUE THREAD

**Issue by kuldeepsingh33** [kuldeepsingh33/DSA-Basic#3]

**Comment by void-57** [comment]
hey @kuldeepsingh33 please assign me

**Comment by MrJayendra** [comment]
I am interested in this work.
Please assign it to me.

**Comment by EnggKrishna** [comment]
Hii 
@kuldeepsingh33 Please assign it to me

**Comment by MrJayendra** [comment]
It's already assigned to me
