### ISSUE TITLE
Basic Sorting Algorithm Implementation In JavaScript

### ISSUE THREAD

**Issue by kuldeepsingh33** [kuldeepsingh33/DSA-Basic#39]

**Comment by cereal-hecker** [comment]
hey, pls assign me this

**Comment by deepesh85b** [comment]
@kuldeepsingh33 
Please assign this to me

**Comment by Nimesh-21** [comment]
Can you please assign this to me? I am new to open source.

**Comment by Subhajit767** [comment]
I want to work on this so please assign this to me
