### ISSUE TITLE
Add Selection  Sort code In Java

### ISSUE THREAD

**Issue by kuldeepsingh33** [kuldeepsingh33/DSA-Basic#5]

**Comment by Frey0-0** [comment]
@kuldeepsingh33 assign this issue to me please

**Comment by kuldeepsingh33** [comment]
ok,  
Now you can work on it.

**Comment by kuldeepsingh33** [comment]
@Frey0-0 , Now you can work on it , add description also what is Selection Sort and how algo work.

**Comment by RavishGupta** [comment]
assign me this issue

**Comment by kuldeepsingh33** [comment]
@Frey0-0 AS you are not made any request till now , so i am assigning this issue @RavishGupta

**Comment by kuldeepsingh33** [comment]
@RavishGupta ,Now you can work on it .

**Comment by kuldeepsingh33** [comment]
@RavishGupta ,show some love mark star on repo.
